// --- ./src/app/dashboard/estimations/drafts/page.tsx ---
"use client";

import { useEffect, useState } from "react";
import { Calculator, Loader2 } from "lucide-react";
import { api } from "@/lib/api";

export default function DraftsPage() {
  const [assessments, setAssessments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get("/assessments/").then(data => {
      setAssessments(data);
      setLoading(false);
    }).catch(console.error);
  }, []);

  return (
    <div className="flex flex-col gap-6 animate-in fade-in duration-500">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">Drafts & Sent Estimates</h1>
        <p className="text-zinc-500 dark:text-zinc-400 mt-1">History of system benchmarks generated by your account.</p>
      </div>

      <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-card-dark shadow-sm overflow-hidden">
        {loading ? <div className="p-12 flex justify-center"><Loader2 className="animate-spin text-brand-primary" /></div> : 
         assessments.length === 0 ? <div className="p-12 text-center text-zinc-500">No assessments created yet.</div> : (
          <table className="w-full text-left text-sm">
            <thead className="bg-zinc-50 dark:bg-zinc-900/50 text-zinc-500 dark:text-zinc-400 border-b border-zinc-200 dark:border-zinc-800">
              <tr>
                <th className="px-5 py-3 font-medium">Date</th>
                <th className="px-5 py-3 font-medium">Vehicle</th>
                <th className="px-5 py-3 font-medium">Provider</th>
                <th className="px-5 py-3 font-medium">LMG Benchmark</th>
                <th className="px-5 py-3 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-200 dark:divide-zinc-800">
              {assessments.map(a => {
                const totalBenchmark = a.total_manufacturing_price + a.total_labor + a.total_paint;
                return (
                  <tr key={a.id} className="hover:bg-zinc-50 dark:hover:bg-zinc-800/30">
                    <td className="px-5 py-4 text-zinc-500">{new Date(a.created_at).toLocaleDateString()}</td>
                    <td className="px-5 py-4 font-medium text-zinc-900 dark:text-zinc-100">{a.vehicles?.make} {a.vehicles?.model}</td>
                    <td className="px-5 py-4 text-zinc-600 dark:text-zinc-300">{a.provider_name}</td>
                    <td className="px-5 py-4 font-mono font-bold text-brand-primary">R {totalBenchmark.toLocaleString()}</td>
                    <td className="px-5 py-4"><span className="px-2 py-1 bg-zinc-100 dark:bg-zinc-800 rounded text-xs uppercase font-semibold">{a.status}</span></td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}